### PR TITLE
Use Docker Host env

### LINKED ISSUE #10: Running on a Mac
- Install [Boot2Docker](https://github.com/boot2docker/boot2docker)

This gets it running:

``` console
boot2docker up
$(boot2docker shellinit)
docker run -d -p 6379:6379 --name redis-master crosbymichael/redis

cd server
go build
./server -r=$(boot2docker ip 2>/dev/null):6379
```

### PR DESCRIPTION
**Pull request by nathany**
This is an easy way to get it working on a Mac. Not sure if it still all works on Linux and how it affects the deploy.

closes #10

### CODE REVIEW

**Comment by vieux** [comment]
Thanks!

I'm actually using [swarm](http://github.com/docker/swarm) instead of docker directly.
So I would prefer a flag. Let's replace `-s` with `-H` like docker and so 

`./server -H $DOCKER_HOST` in the readme.

**Comment by nathany** [comment]
Sounds good.

**Comment by nathany** [comment]
PTAL

**Comment by vieux** [comment]
@nathany LGTM sorry to bother you, but can you use the official redis images instead of `crosbymichael/redis`

Thanks

**Comment by nathany** [comment]
sure, no problem.

if you tire of waiting for contributors to make a small change, check out:
http://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/

**Pull request closed without merging**
